### ISSUE TITLE
refactors

### ISSUE THREAD

**Issue by zndrr** [zndrr/nb#3]
Lots of time has elapsed since this endeavour to create an install script.

## TODO
- [ ] Split out install stages to separate files.
- [ ] Consider removing install methods that aren't Git cloning.
- [ ] Consider Docker method.
